=== IsraelHG/solvd-laba-concerthalldb/src/main/resources/event.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="event">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="eventId" type="xs:int"/>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="startDate" type="xs:dateTime"/>
                <xs:element name="endDate" type="xs:dateTime"/>
                <xs:element name="venues">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="venue" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="venueId" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="city" type="xs:string"/>
                                        <xs:element name="state" type="xs:string"/>
                                        <xs:element name="capacity" type="xs:int"/>
                                        <xs:element name="website" type="xs:anyURI"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="artists">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="artist" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="artistId" type="xs:int"/>
                                        <xs:element name="firstName" type="xs:string"/>
                                        <xs:element name="lastName" type="xs:string"/>
                                        <xs:element name="genre" type="xs:string"/>
                                        <xs:element name="email" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="equipments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="equipment" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="equipmentId" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="quantity" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sponsors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sponsor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sponsorId" type="xs:int"/>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="sponsorshipAmount" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== IsraelHG/solvd-laba-concerthalldb/src/main/resources/event.xml
<?xml version="1.0" encoding="UTF-8"?>
<event xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="event.xsd">
    <eventId>1</eventId>
    <name>Event 1</name>
    <startDate>2023-06-01T10:00:00</startDate>
    <endDate>2023-06-02T18:00:00</endDate>
    <venues>
        <venue>
            <venueId>1</venueId>
            <name>Venue 1</name>
            <city>City 1</city>
            <state>State 1</state>
            <capacity>1000</capacity>
            <website>http://www.example.com/venue1</website>
        </venue>
        <venue>
            <venueId>2</venueId>
            <name>Venue 2</name>
            <city>City 2</city>
            <state>State 2</state>
            <capacity>2000</capacity>
            <website>http://www.example.com/venue2</website>
        </venue>
    </venues>
    <artists>
        <artist>
            <artistId>1</artistId>
            <firstName>Freddy</firstName>
            <lastName>Mercury</lastName>
            <genre>Rock</genre>
            <email>freddy.mercury@gmail.com</email>
        </artist>
    </artists>
    <equipments>
        <equipment>
            <equipmentId>1</equipmentId>
            <name>Guitar</name>
            <quantity>5</quantity>
        </equipment>
    </equipments>
    <sponsors>
        <sponsor>
            <sponsorId>1</sponsorId>
            <name>Company A</name>
            <sponsorshipAmount>1000.00</sponsorshipAmount>
        </sponsor>
    </sponsors>
</event>
